In [1]:
#Import Libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv("D:\\AML-Lab\\Project-1\\data\\bestsellers.csv")
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2019,Non Fiction

In [4]:
print(df.head(5))
print(df.info())
print(df.duplicated().sum())
print(df.isnull().sum())

                                                Name  \
0                      10-Day Green Smoothie Cleanse
1                                  11/22/63: A Novel
2            12 Rules for Life: An Antidote to Chaos
3                             1984 (Signet Classics)
4  5,000 Awesome Facts (About Everything!) (Natio...

                     Author  User Rating  Reviews  Price  Year        Genre
0                  JJ Smith          4.7  17350.0    8.0  2016  Non Fiction
1              Stephen King          4.6   2052.0   22.0  2011      Fiction
2        Jordan B. Peterson          4.7  18979.0   15.0  2018  Non Fiction
3             George Orwell          4.7  21424.0    6.0  2017      Fiction
4  National Geographic Kids          4.8   7665.0   12.0  2019  Non Fiction
<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB
None
0
Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [6]:
df["User Rating"] = df["User Rating"].fillna(df["User Rating"].median())

In [7]:
df["Reviews"] = df["Reviews"].fillna(df["Reviews"].median())
df["Price"] = df["Price"].fillna(df["Price"].median())

In [8]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

Name               str
Author             str
User Rating    float64
Reviews        float64
Price          float64
Year             int64
Genre              str
dtype: object

In [11]:
df["Genre"].value_counts()

Genre
Non Fiction    310
Fiction        240
Name: count, dtype: int64

In [12]:
df=df.drop("Name",axis=1)
df.head()

                     Author  User Rating  Reviews  Price  Year        Genre
0                  JJ Smith          4.7  17350.0    8.0  2016  Non Fiction
1              Stephen King          4.6   2052.0   22.0  2011      Fiction
2        Jordan B. Peterson          4.7  18979.0   15.0  2018  Non Fiction
3             George Orwell          4.7  21424.0    6.0  2017      Fiction
4  National Geographic Kids          4.8   7665.0   12.0  2019  Non Fiction

In [13]:
X = df.drop("Genre",axis=1)
y = df["Genre"]

In [14]:
X.head()

                     Author  User Rating  Reviews  Price  Year
0                  JJ Smith          4.7  17350.0    8.0  2016
1              Stephen King          4.6   2052.0   22.0  2011
2        Jordan B. Peterson          4.7  18979.0   15.0  2018
3             George Orwell          4.7  21424.0    6.0  2017
4  National Geographic Kids          4.8   7665.0   12.0  2019

In [15]:
y.head()

0    Non Fiction
1        Fiction
2    Non Fiction
3        Fiction
4    Non Fiction
Name: Genre, dtype: str

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [17]:
X_train

                          Author  User Rating  Reviews  Price  Year
326                 Gary Chapman          4.8  25554.0    8.0  2016
529                    Adir Levy          4.8   8170.0   13.0  2019
327                 Gary Chapman          4.8  25554.0    8.0  2017
76                 Veronica Roth          4.6  27098.0   15.0  2014
123                Giles Andreae          4.8  14038.0    4.0  2015
..                           ...          ...      ...    ...   ...
403             Kathryn Stockett          4.8  13871.0    6.0  2010
50                  Francis Chan          4.7   1542.0   14.0  2009
196                Bill O'Reilly          4.5  11391.0   12.0  2013
447                 Ree Drummond          4.8   3428.0   14.0  2015
15   Adult Coloring Book Designs          4.5   2313.0    4.0  2016

[440 rows x 5 columns]

In [18]:
X_test

                                 Author  User Rating  Reviews  Price  Year
220                          Celeste Ng          4.5  25706.0   12.0  2018
51                         Francis Chan          4.7   1542.0   14.0  2010
274  American Psychological Association          4.5   8580.0   46.0  2012
119                  George R.R. Martin          4.6   5594.0    5.0  2012
450              Dr. Steven R Gundry MD          4.4   7058.0   17.0  2018
..                                  ...          ...      ...    ...   ...
394                 F. Scott Fitzgerald          4.4  11616.0    7.0  2012
57                     Abraham Verghese          4.6   4866.0   11.0  2011
269                      Eben Alexander          4.3  13616.0   10.0  2012
542                       R. J. Palacio          4.8  21625.0    9.0  2015
474                         Jeff Kinney          4.8   3796.0   12.0  2010

[110 rows x 5 columns]

In [20]:
X_train.shape

(440, 5)

In [21]:
X_test.shape

(110, 5)

In [19]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore',sparse_output=False)

In [22]:
author_train = encoder.fit_transform(X_train[["Author"]])

In [23]:
author_test = encoder.transform(X_test[["Author"]])

In [24]:
author_train.shape

(440, 222)

In [25]:
numerical_cols = ["User Rating", "Reviews", "Price", "Year"]

In [26]:
scaler = StandardScaler()
numeric_train = scaler.fit_transform(X_train[numerical_cols])
numeric_test = scaler.transform(X_test[numerical_cols])

In [28]:
print(numeric_train.shape)
print(numeric_test.shape)

(440, 4)
(110, 4)

In [29]:
X_train_final=np.hstack([author_train,numeric_train])
X_test_final=np.hstack([author_test,numeric_test])

In [30]:
print(X_train_final.shape)
print(X_test_final.shape)

(440, 226)
(110, 226)

In [31]:
numeric_train.mean(axis=0)

array([ 1.45035499e-15,  8.07434927e-17,  4.03717464e-17, -5.25640137e-15])

In [32]:
numeric_train.std(axis=0)

array([1., 1., 1., 1.])