In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
df=pd.read_csv('D:/AML-Lab/Project-1/data/Groceries_dataset.csv')
df

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [5]:
df.head(5)

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [6]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  str
 2   itemDescription  38765 non-null  str
dtypes: int64(1), str(2)
memory usage: 908.7 KB

Member_number      0
Date               0
itemDescription    0
dtype: int64

In [7]:
#Checking for duplicates
df.duplicated().sum()

np.int64(759)

In [8]:
#Removing the duplicates

df=df.drop_duplicates()

print("Duplicates after removal: ", df.duplicated().sum())
print("Rows remaining after removal: ", len(df))

Duplicates after removal:  0
Rows remaining after removal:  38006

In [9]:
df["Date"] = pd.to_datetime(df["Date"],format='%d-%m-%Y')

print("Checking if any error dates are present: ", df["Date"].isnull().sum())

df.head()

Checking if any error dates are present:  0

   Member_number       Date   itemDescription
0           1808 2015-07-21    tropical fruit
1           2552 2015-01-05        whole milk
2           2300 2015-09-19         pip fruit
3           1187 2015-12-12  other vegetables
4           3037 2015-02-01        whole milk

In [10]:
# Remove extra spaces and standardize capitalization
df["itemDescription"] = (
    df["itemDescription"]
    .str.strip()
    .str.lower()
)

df.head()

   Member_number       Date   itemDescription
0           1808 2015-07-21    tropical fruit
1           2552 2015-01-05        whole milk
2           2300 2015-09-19         pip fruit
3           1187 2015-12-12  other vegetables
4           3037 2015-02-01        whole milk

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 38006 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38006 non-null  int64
 1   Date             38006 non-null  datetime64[us]
 2   itemDescription  38006 non-null  str
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 1.2 MB

In [12]:
df = df.reset_index(drop=True)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 38006 entries, 0 to 38005
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38006 non-null  int64
 1   Date             38006 non-null  datetime64[us]
 2   itemDescription  38006 non-null  str
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 890.9 KB

   Member_number       Date   itemDescription
0           1808 2015-07-21    tropical fruit
1           2552 2015-01-05        whole milk
2           2300 2015-09-19         pip fruit
3           1187 2015-12-12  other vegetables
4           3037 2015-02-01        whole milk

In [13]:
from sklearn.preprocessing import LabelEncoder

#Features

X=df[["Member_number","Date"]].copy()

X["Date"] = X["Date"].map(pd.Timestamp.toordinal)

y=df["itemDescription"]

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)

(30404, 2)
(7602, 2)

In [18]:
X_test

array([[-1.71256225, -0.140707  ],
       [-0.2077696 , -0.00714417],
       [ 1.71881443,  0.69406071],
       ...,
       [-1.11099092,  0.54618757],
       [ 0.72829612,  1.13768013],
       [-1.3797965 ,  0.54618757]], shape=(7602, 2))

In [19]:
X_train

array([[-0.44632375, -1.40955393],
       [ 0.05066406, -0.1263967 ],
       [-0.81106958, -0.66541814],
       ...,
       [ 0.78534168, -0.54616561],
       [-1.42906312,  0.36969383],
       [-1.69614004,  1.61946035]], shape=(30404, 2))